-- CreateTable
CREATE TABLE "Listing" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "type" TEXT,
    "price" INTEGER NOT NULL,
    "size" REAL,
    "unit" TEXT,
    "region" TEXT,
    "district" TEXT,
    "ward" TEXT,
    "village" TEXT,
    "lat" TEXT,
    "lon" TEXT,
    "road" TEXT,
    "roadcond" TEXT,
    "deed" TEXT,
    "topo" TEXT,
    "soil" TEXT,
    "utilities" TEXT,
    "amenities" TEXT,
    "desc" TEXT,
    "contactName" TEXT,
    "contactPhone" TEXT,
    "contactPreferred" TEXT,
    "contactEmail" TEXT,
    "contactRole" TEXT,
    "contactNotes" TEXT,
    "images" TEXT,
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "color" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
