const prisma = require('./prisma');

const sampleListings = [
  {
    title: 'Shamba la Kilimo Morogoro – Hektari 12 za Mazao',
    type: 'Agricultural',
    price: 32000000,
    size: 12,
    unit: 'Hektari',
    region: 'Morogoro',
    district: 'Morogoro',
    ward: 'Boma',
    village: 'Kibaoni',
    lat: '-6.827',
    lon: '37.660',
    road: '0.7 km kutoka barabara ya lami',
    roadcond: 'Paved access',
    deed: 'Surveyed – Pending',
    topo: 'Bapa',
    soil: 'Udongo wa Mbolea',
    utilities: ['Water', 'Electricity', 'Borehole'],
    amenities: '1 km shule, 3 km soko, 8 km hospitali',
    desc: 'Shamba la kilimo lenye mpango wa uzalishaji wa mazao ya matunda na mboga. Lina maji ya kisima, umeme, na njia za kupitisha bidhaa kwa soko la Dar es Salaam.',
    images: [
      'https://images.unsplash.com/photo-1464226184612-280ebc17f399?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1591863571934-2c3470ca018d?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    color: 'from-green',
    contact: {
      name: 'Amina Hassan',
      phone: '+255 717 123 456',
      preferred: 'WhatsApp',
      email: 'amina@example.com',
      notes: 'Inapendekezwa kwa wakulima wa umwagiliaji na wawekezaji wa kilimo.',
    },
  },
  {
    title: 'Kiwanja cha Makazi Mbeya – Ekari 0.7 kwa Ujenzi wa Nyumba',
    type: 'Residential',
    price: 45000000,
    size: 0.7,
    unit: 'Ekari',
    region: 'Mbeya',
    district: 'Mbeya Mjini',
    ward: 'Isanga',
    village: 'Sanje',
    lat: '-8.910',
    lon: '33.450',
    road: '3 km kutoka barabara ya lami',
    roadcond: 'Gravel road',
    deed: 'Registered Title Deed',
    topo: 'Bapa',
    soil: 'Udongo wa Mbolea',
    utilities: ['Water', 'Electricity', 'Internet'],
    amenities: '5 km kutoka soko, 2 km shule, 4 km kituo cha polisi',
    desc: 'Kiwanja safi kwa nyumba ya familia au jengo la kukodisha. Karibu na miundombinu ya msingi, kinatoa nafasi ya maendeleo ya makazi ya kiwango cha juu.',
    images: [
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: false,
    color: 'from-blue',
    contact: {
      name: 'Asha Mase',
      phone: '+255 713 654 321',
      preferred: 'Phone',
      email: 'asha@example.com',
      notes: 'Kiwanja kinapatikana mara moja kwa mnunuzi anayetafuta makazi.',
    },
  },
  {
    title: 'Kiwanja cha Biashara Dar – Eneo la Mbezi Beach',
    type: 'Commercial',
    price: 105000000,
    size: 0.35,
    unit: 'Ekari',
    region: 'Dar es Salaam',
    district: 'Kinondoni',
    ward: 'Mbezi Beach',
    village: 'Mbezi Tisa',
    lat: '-6.734',
    lon: '39.170',
    road: 'Moja kwa moja kutoka barabara kuu',
    roadcond: 'Paved access',
    deed: 'Registered Title Deed',
    topo: 'Bapa',
    soil: 'Udongo wa Mbolea',
    utilities: ['Water', 'Electricity', 'Internet', 'Fence'],
    amenities: '1 km soko, 2 km hospitali, 1.5 km bandari ya viungo',
    desc: 'Kiwanja cha biashara kwenye eneo lenye watu wengi. Kinafaa kwa maduka ya rejareja, ofisi ndogo, au kituo cha huduma za mtaa.',
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    color: 'from-amber',
    contact: {
      name: 'Moses Komba',
      phone: '+255 716 890 123',
      preferred: 'WhatsApp',
      email: 'moses@example.com',
      notes: 'Inafaa kwa wawekezaji wa maduka ya rejareja au viwanja vya biashara.',
    },
  },
  {
    title: 'Kiwanja cha Biashara Arusha – Karibu na Uwanja wa Ndege',
    type: 'Commercial',
    price: 78000000,
    size: 0.45,
    unit: 'Ekari',
    region: 'Arusha',
    district: 'Arusha Mjini',
    ward: 'Sombetini',
    village: 'Ngaramtoni',
    lat: '-3.395',
    lon: '36.684',
    road: '1.2 km kutoka barabara ya lami',
    roadcond: 'Paved access',
    deed: 'Surveyed – Pending',
    topo: 'Bapa',
    soil: 'Udongo wa Mbolea',
    utilities: ['Water', 'Electricity', 'Internet'],
    amenities: '2 km kutoka uwanja wa ndege, 1 km soko, 3 km hospitali',
    desc: 'Kiwanja cha biashara kimoja kwa moja kwa maduka, ofisi za utalii, au huduma za viwanja vya ndege.',
    images: [
      'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: false,
    color: 'from-purple',
    contact: {
      name: 'Nadia Selemani',
      phone: '+255 754 334 221',
      preferred: 'Phone',
      email: 'nadia@example.com',
      notes: 'Muuzaji anatafuta mnunuzi wa biashara wa muda mfupi.',
    },
  },
  {
    title: 'Kiwanja cha Makazi Arusha – Ekari 1 kwa Mpango wa Nyumba',
    type: 'Residential',
    price: 62000000,
    size: 1,
    unit: 'Ekari',
    region: 'Arusha',
    district: 'Arusha Mjini',
    ward: 'Kati',
    village: 'Oldonyo',
    lat: '-3.386',
    lon: '36.682',
    road: '1 km kutoka barabara ya lami',
    roadcond: 'Paved access',
    deed: 'Registered Title Deed',
    topo: 'Bapa',
    soil: 'Udongo wa Mbolea',
    utilities: ['Water', 'Electricity', 'Internet'],
    amenities: '2 km kutoka shule, 3 km mji wa Arusha, 5 km uwanja',
    desc: 'Kiwanja cha makazi kilicho karibu na mji wa Arusha, kikiwa na mpango wa nyumba ya kifamilia.',
    images: [
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: true,
    color: 'from-cyan',
    contact: {
      name: 'Fatuma Mwanga',
      phone: '+255 784 234 567',
      preferred: 'WhatsApp',
      email: 'fatuma@example.com',
      notes: 'Inafaa kwa ujenzi wa nyumba ya kifamilia au mradi wa nyumba za kukodisha.',
    },
  },
  {
    title: 'Shamba la Kilimo Iringa – Ekari 8 kwa Kahawa na Nyumba',
    type: 'Agricultural',
    price: 29000000,
    size: 8,
    unit: 'Hektari',
    region: 'Iringa',
    district: 'Kilolo',
    ward: 'Udekwa',
    village: 'Kimani',
    lat: '-7.719',
    lon: '35.691',
    road: '1.5 km kutoka barabara ya changarawe',
    roadcond: 'Gravel road',
    deed: 'Registered Title Deed',
    topo: 'Mteremko Mdogo',
    soil: 'Udongo wa Mbolea',
    utilities: ['Water', 'Electricity', 'Borehole'],
    amenities: '4 km kutoka soko, 2 km shule, 6 km kituo cha afya',
    desc: 'Shamba ya kilimo yenye udongo mzuri kwa kahawa, miembe, au mboga, pamoja na mpango wa nyumba ya msimamizi wa shamba.',
    images: [
      'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500534314209-a9c8ff223c5d?auto=format&fit=crop&w=1200&q=80',
    ],
    featured: false,
    color: 'from-green',
    contact: {
      name: 'Juma Mwinyi',
      phone: '+255 755 987 654',
      preferred: 'WhatsApp',
      email: 'juma@example.com',
      notes: 'Inafaa kwa wakulima wa kahawa, matunda, au mradi wa nyumba za msimamizi wa shamba.',
    },
  },
];

function toDbRecord(listing) {
  return {
    title: listing.title,
    type: listing.type,
    price: listing.price,
    size: listing.size,
    unit: listing.unit,
    region: listing.region,
    district: listing.district,
    ward: listing.ward,
    village: listing.village,
    lat: listing.lat,
    lon: listing.lon,
    road: listing.road,
    roadcond: listing.roadcond,
    deed: listing.deed,
    topo: listing.topo,
    soil: listing.soil,
    utilities: JSON.stringify(listing.utilities || []),
    amenities: listing.amenities,
    desc: listing.desc,
    contactName: listing.contact?.name || null,
    contactPhone: listing.contact?.phone || null,
    contactPreferred: listing.contact?.preferred || null,
    contactEmail: listing.contact?.email || null,
    contactRole: listing.contact?.role || null,
    contactNotes: listing.contact?.notes || null,
    images: JSON.stringify(listing.images || []),
    featured: Boolean(listing.featured),
    color: listing.color || null,
  };
}

async function main() {
  const existing = await prisma.listing.count();
  if (existing > 0) {
    console.log(`Database already has ${existing} listings — skipping seed.`);
    return;
  }

  console.log('Seeding database with sample listings...');
  for (const listing of sampleListings) {
    await prisma.listing.create({ data: toDbRecord(listing) });
  }

  const count = await prisma.listing.count();
  console.log(`Seed complete. ${count} listings in database.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
